'use strict';
/**
 * guardrails.js — Validation & safety layer for the tax advisor
 *
 * Pure logic, no I/O — fully unit-testable. Everything here runs on the AI's
 * response BEFORE it is shown to the user, plus pre-flight risk detection on the
 * user's question.
 *
 * Responsibilities:
 *   - Detect high-risk topics that warrant professional escalation
 *   - Verify the answer cites its sources
 *   - Verify any dollar amounts in the answer are "grounded" (came from the
 *     deterministic engine or a retrieved source — never invented by the model)
 *   - Verify the answer references the correct tax year
 *   - Decide when to escalate to a CPA / EA / tax attorney
 *   - Provide the standard disclaimer
 */

// ─── Risk topic patterns ───────────────────────────────────────────────────────
// Each flag has a severity. 'critical' → always escalate to a professional.
const RISK_PATTERNS = [
  { flag: 'audit',                severity: 'critical', re: /\b(audit(ed|ing|s)?|examination|irs notice|notice cp|cp ?2000|cp\d{2,4}|letter \d{3,4})\b/i },
  { flag: 'penalty',              severity: 'high',     re: /\b(penalt(y|ies)|back tax(es)?|tax debt|lien|levy|garnish)/i },
  { flag: 'foreign',              severity: 'critical', re: /\b(foreign (account|income|asset|bank)|fbar|fatca|form 8938|offshore|expat)/i },
  { flag: 'crypto',               severity: 'high',     re: /\b(crypto(currency)?|bitcoin|ethereum|nft|digital asset|staking|airdrop)/i },
  { flag: 'payroll',              severity: 'critical', re: /\b(payroll tax|employment tax|941|940|w-?2 employee|withholding deposit|trust fund)/i },
  { flag: 'multi_state',          severity: 'high',     re: /\b(multi.?state|multiple states|moved (from|to) (another )?state|nonresident return|state allocation|nexus)\b/i },
  { flag: 'entity_structure',     severity: 'critical', re: /\b(s.?corp|c.?corp|llc election|partnership formation|incorporat|entity (choice|selection|structure)|elect s)/i },
  { flag: 'large_capital_gains',  severity: 'high',     re: /\b(large (capital )?gain|sell(ing)? (my )?(business|company)|qsbs|1202|installment sale|like.?kind|1031 exchange)/i },
  { flag: 'irs_dispute',          severity: 'critical', re: /\b(innocent spouse|offer in compromise|appeal|tax court|collection due process|cnc status)/i },
  { flag: 'estate_gift',          severity: 'high',     re: /\b(estate tax|gift tax|inheritance|form 706|form 709|trust (income|return)|gst tax)/i },
];

// Dollar amount regex — matches $1,234 / $1234.56 / $1.2 million etc.
const DOLLAR_RE = /\$\s?\d[\d,]*(?:\.\d+)?(?:\s?(?:million|billion|k|m|b))?/gi;

// ─── The disclaimer ─────────────────────────────────────────────────────────────
const DISCLAIMER =
  'This is general tax information generated by an AI assistant, based on the ' +
  'sources cited above and your provided data. It is not professional tax advice. ' +
  'Tax situations are individual and the law is complex — verify important ' +
  'decisions with a licensed CPA, Enrolled Agent, or tax attorney before acting.';

const ESCALATION_NOTE =
  'Because your question touches on a higher-risk area, I strongly recommend ' +
  'reviewing it with a qualified tax professional (CPA, Enrolled Agent, or tax ' +
  'attorney) before taking any action.';

// ─────────────────────────────────────────────────────────────────────────────

/**
 * Detect risk flags in a piece of text (usually the user's question).
 * @param {string} text
 * @returns {Array<{flag:string, severity:string}>}
 */
function detectRiskFlags(text) {
  if (!text) return [];
  const found = [];
  for (const { flag, severity, re } of RISK_PATTERNS) {
    if (re.test(text)) found.push({ flag, severity });
  }
  return found;
}

/** Decide whether to escalate based on detected flags. */
function shouldEscalate(flags) {
  const critical = flags.filter(f => f.severity === 'critical');
  if (critical.length) {
    return { escalate: true, reason: `Critical-risk topic(s): ${critical.map(f => f.flag).join(', ')}` };
  }
  // Two or more 'high' flags together also escalate
  const high = flags.filter(f => f.severity === 'high');
  if (high.length >= 2) {
    return { escalate: true, reason: `Multiple higher-risk topics: ${high.map(f => f.flag).join(', ')}` };
  }
  return { escalate: false, reason: null };
}

/**
 * Does the answer contain at least one citation referencing the provided sources?
 * Accepts "[Source 1]" style markers OR a source's name appearing verbatim.
 * @param {string} answer
 * @param {Array<{sourceName:string}>} sources
 */
function checkCitations(answer, sources = []) {
  if (!answer) return { hasCitations: false, citationCount: 0 };
  const markerMatches = answer.match(/\[Source\s+\d+\]/gi) || [];
  let nameMatches = 0;
  for (const s of sources) {
    if (s.sourceName && answer.includes(s.sourceName)) nameMatches++;
  }
  // Also count common citation phrasing like "Per IRS Publication 587" / "IRC §280A"
  const phraseMatches = (answer.match(/\b(per|under|according to|see)\b[^.]{0,40}\b(IRS|IRC|Publication|Pub\.?|Form|Schedule|§)\b/gi) || []).length;
  const total = markerMatches.length + nameMatches + phraseMatches;
  return { hasCitations: total > 0, citationCount: total };
}

/** Extract normalized dollar amounts (as strings of digits) from text. */
function extractDollarAmounts(text) {
  if (!text) return [];
  const matches = text.match(DOLLAR_RE) || [];
  return matches.map(m => normalizeAmount(m)).filter(Boolean);
}

function normalizeAmount(raw) {
  let s = raw.toLowerCase().replace(/[$,\s]/g, '');
  let mult = 1;
  if (/million|m$/.test(s)) { mult = 1e6; s = s.replace(/million|m$/,''); }
  else if (/billion|b$/.test(s)) { mult = 1e9; s = s.replace(/billion|b$/,''); }
  else if (/k$/.test(s)) { mult = 1e3; s = s.replace(/k$/,''); }
  const n = parseFloat(s);
  if (isNaN(n)) return null;
  return String(Math.round(n * mult));
}

/**
 * Collect the set of dollar amounts that the answer is ALLOWED to state —
 * i.e. numbers that came from the deterministic engine or appear in a source.
 * @param {object|null} calculationResult  full TaxResult (has steps[] + top-level numbers)
 * @param {Array<{text:string}>} sources
 * @returns {Set<string>} normalized amount strings
 */
function collectGroundedNumbers(calculationResult, sources = []) {
  const grounded = new Set();

  const addNum = (n) => {
    if (typeof n === 'number' && isFinite(n)) {
      grounded.add(String(Math.round(Math.abs(n))));
    }
  };

  if (calculationResult) {
    // Top-level numeric fields
    for (const v of Object.values(calculationResult)) addNum(v);
    // Step values
    for (const step of calculationResult.steps || []) {
      addNum(step.value);
      // amounts embedded in the formula string
      extractDollarAmounts(step.formula || '').forEach(a => grounded.add(a));
    }
    // Bracket breakdowns
    for (const b of calculationResult.bracketBreakdown?.ordinary || []) {
      addNum(b.tax); addNum(b.taxable);
    }
  }

  // Amounts appearing in retrieved sources (e.g. "$14,600 standard deduction")
  for (const s of sources) {
    extractDollarAmounts(s.text || '').forEach(a => grounded.add(a));
  }

  return grounded;
}

/**
 * Flag dollar amounts in the answer that are NOT grounded in the engine or sources.
 * Tolerates rounding to the nearest dollar. Returns the ungrounded amounts.
 * @param {string} answer
 * @param {Set<string>} grounded
 */
function checkNumbersGrounded(answer, grounded) {
  const inAnswer = extractDollarAmounts(answer);
  const ungrounded = [];
  for (const amt of inAnswer) {
    if (grounded.has(amt)) continue;
    // tolerate ±1 rounding and the trivial "$0"
    const n = parseInt(amt, 10);
    if (n === 0) continue;
    if (grounded.has(String(n + 1)) || grounded.has(String(n - 1))) continue;
    ungrounded.push(amt);
  }
  return { allGrounded: ungrounded.length === 0, ungrounded };
}

/** Check the answer references the expected tax year (when one is in play). */
function checkTaxYear(answer, expectedYear) {
  if (!expectedYear || !answer) return { correctYear: true, mentionedYears: [] };
  const years = (answer.match(/\b(20\d\d)\b/g) || []).map(Number);
  const uniqueYears = [...new Set(years)];
  // OK if it mentions the expected year, or mentions no year at all.
  const wrongYears = uniqueYears.filter(y => y !== expectedYear && y >= 2015 && y <= 2030);
  const correctYear = uniqueYears.length === 0 || uniqueYears.includes(expectedYear);
  return { correctYear, mentionedYears: uniqueYears, wrongYears };
}

/**
 * Run the full validation suite on an AI answer.
 * @param {object} args
 * @param {string} args.answer
 * @param {Array}  args.sources
 * @param {object|null} args.calculationResult
 * @param {number} [args.taxYear]
 * @param {Array}  [args.riskFlags]
 * @returns {object} validation result with .passed and .details
 */
function validateAnswer({ answer, sources = [], calculationResult = null, taxYear, riskFlags = [], extraGroundingText = '' }) {
  const citations = checkCitations(answer, sources);
  // User-provided data (e.g. "my W-2 is $200,000") legitimately grounds numbers
  // the user themselves stated, so fold it in as an extra grounding source.
  const groundingSources = extraGroundingText
    ? [...sources, { text: extraGroundingText }]
    : sources;
  const grounded  = collectGroundedNumbers(calculationResult, groundingSources);
  const numbers   = checkNumbersGrounded(answer, grounded);
  const yearCheck = checkTaxYear(answer, taxYear);

  const details = {
    hasCitations:      citations.hasCitations,
    citationCount:     citations.citationCount,
    numbersGrounded:   numbers.allGrounded,
    ungroundedAmounts: numbers.ungrounded,
    correctYear:       yearCheck.correctYear,
    mentionedYears:    yearCheck.mentionedYears,
    sourcesProvided:   sources.length,
  };

  // Blocking issues: wrong tax year, or ungrounded numbers when a calc was run.
  const blocking = [];
  if (!yearCheck.correctYear) {
    blocking.push(`Answer references tax year(s) ${yearCheck.wrongYears.join(', ')} but the question is about ${taxYear}`);
  }
  if (calculationResult && !numbers.allGrounded) {
    blocking.push(`Answer contains dollar amounts not produced by the tax engine: ${numbers.ungrounded.map(a => '$' + Number(a).toLocaleString()).join(', ')}`);
  }

  // Warnings: no citations when sources were available.
  const warnings = [];
  if (sources.length > 0 && !citations.hasCitations) {
    warnings.push('Answer does not cite any of the retrieved sources');
  }
  if (!calculationResult && numbers.ungrounded.length > 0 && sources.length === 0) {
    warnings.push('Answer states dollar amounts with no engine calculation or sources to support them');
  }

  return {
    passed: blocking.length === 0,
    blocking,
    warnings,
    details,
  };
}

module.exports = {
  RISK_PATTERNS,
  DISCLAIMER,
  ESCALATION_NOTE,
  detectRiskFlags,
  shouldEscalate,
  checkCitations,
  extractDollarAmounts,
  normalizeAmount,
  collectGroundedNumbers,
  checkNumbersGrounded,
  checkTaxYear,
  validateAnswer,
};
